Document: amxa-client-media
Title: Debian amxa-client-media Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-client-media is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-client-media/amxa-client-media.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-client-media/amxa-client-media.ps.gz

Format: text
Files: /usr/share/doc/amxa-client-media/amxa-client-media.text.gz

Format: HTML
Index: /usr/share/doc/amxa-client-media/html/index.html
Files: /usr/share/doc/amxa-client-media/html/*.html
